---
include:
  - board: nice_nano_v2
    shield: crosses_left
    artifact-name: crosses_54_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: crosses_right
    artifact-name: crosses_54_right
    snippet: 'studio-rpc-usb-uart" -S "zmk-usb-logging'
    cmake-args: -DCONFIG_ZMK_STUDIO=y
